### ISSUE TITLE
Understanding your audience

### ISSUE THREAD

**Issue by zapman449** [keithjgrant/Taming-CSS#3]
Who is the audience of this book?  Experienced WebDevs? Or ones just getting started?

The first two chapters seem to be aiming at a moderately experienced WebDev.  But chapter 2 goes straight to grade school... it might be valuable, but it doesn't fit the flow of the first two chapters.

**Comment by keithjgrant** [comment]
Yeah, I'm writing primarily for web devs, but I also want to cover the basics so someone starting from square one could really learn everything they need to know from this one resource.  For instance, if the reader is a back-end devs who wants to make the jump to the front end, I want to accommodate them.  I'm still working through how to structure this though, and am open to ideas. Maybe some sort of appendix, and open with a note pointing new learners there first?

**Comment by keithjgrant** [comment]
Okay, I've completely restructured things.  The book is now broken up into Crawling, Walking, Running, and Flying sections, with the basics all in Crawling.  The introduction also sets the stage a bit more clearly, I hope.  Let me know if you have any thoughts on this.  Otherwise, I'll mark this resolved in a day or two.

Again, thanks for the feedback :)
