### ISSUE TITLE
Internal Navigation Links

### ISSUE THREAD

**Issue by secade** [keithjgrant/Taming-CSS#6]
Really enjoying reading the content, but I have a small request- would it be possible to add in 'Back' and 'Next' links to the bottom of each page? I haven't done much large-scale reading of this sort of on Github, but especially on tablets I find having to go back each time to be frustrating.

**Comment by keithjgrant** [comment]
I hear you there.  I haven't done it up until now because I'm trying to keep things mostly platform-agnostic (so publishing later wouldn't require ripping stuff out)... but I think this is a pretty small hassle for a pretty big gain, especially while this lives on Github.  I'll add some links tonight.

**Comment by secade** [comment]
That's awesome. I really like what you have here- I'm a relatively new developer and since I work primarily work on the backend, I have to go out of my way to get practice/experience with the heavier front-end technologies.

**Comment by keithjgrant** [comment]
Glad to hear it :)  Let me know anywhere things can be improved.
